package qt.dto;

// Generated Jun 17, 2010 12:35:19 AM by Hibernate Tools 3.3.0.GA

/**
 * Camera generated by hbm2java
 */
public class Camera implements java.io.Serializable {

	private double doPhanGiaiMayAnh;
	private String moTaMayAnh;

	public Camera() {
	}

	public Camera(double doPhanGiaiMayAnh, String moTaMayAnh) {
		this.doPhanGiaiMayAnh = doPhanGiaiMayAnh;
		this.moTaMayAnh = moTaMayAnh;
	}

	public double getDoPhanGiaiMayAnh() {
		return this.doPhanGiaiMayAnh;
	}

	public void setDoPhanGiaiMayAnh(double doPhanGiaiMayAnh) {
		this.doPhanGiaiMayAnh = doPhanGiaiMayAnh;
	}

	public String getMoTaMayAnh() {
		return this.moTaMayAnh;
	}

	public void setMoTaMayAnh(String moTaMayAnh) {
		this.moTaMayAnh = moTaMayAnh;
	}

}
