package qt.dto;

// Generated Jun 17, 2010 10:03:17 PM by Hibernate Tools 3.3.0.GA

/**
 * ChiTietHinhAnh generated by hbm2java
 */
public class ChiTietHinhAnh implements java.io.Serializable {

	private Integer id;
	private SanPham sanPham;
	private String hinhAnh;
	private boolean xoa;

	public ChiTietHinhAnh() {
	}

	public ChiTietHinhAnh(String hinhAnh, boolean xoa) {
		this.hinhAnh = hinhAnh;
		this.xoa = xoa;
	}

	public ChiTietHinhAnh(SanPham sanPham, String hinhAnh, boolean xoa) {
		this.sanPham = sanPham;
		this.hinhAnh = hinhAnh;
		this.xoa = xoa;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

}
