package qt.dto;

// Generated May 27, 2010 8:56:45 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DonHang generated by hbm2java
 */
@SuppressWarnings("serial")
public class DonHang implements java.io.Serializable {

	private Integer id;
	private Date ngayTao;
	private NguoiNhan nguoiNhan;
	private String diaChiGiaoHang;
	private Date thoiGianGiaoHang;
	private boolean xoa;
	private HinhThucThanhToan hinhThucThanhToan;
	private TrangThaiDonHang trangThai;
	private Set<ChiTietDonHang> dsChiTietDonHang = new HashSet<ChiTietDonHang>(
			0);
	private KhachHang khachHang;

	public DonHang() {
	}

	public DonHang(Date ngayTao, NguoiNhan nguoiNhan, String diaChiGiaoHang,
			Date thoiGianGiaoHang, boolean xoa) {
		this.ngayTao = ngayTao;
		this.nguoiNhan = nguoiNhan;
		this.diaChiGiaoHang = diaChiGiaoHang;
		this.thoiGianGiaoHang = thoiGianGiaoHang;
		this.xoa = xoa;
	}

	public DonHang(Date ngayTao, NguoiNhan nguoiNhan, String diaChiGiaoHang,
			Date thoiGianGiaoHang, boolean xoa,
			HinhThucThanhToan hinhThucThanhToan, TrangThaiDonHang trangThai,
			Set<ChiTietDonHang> dsChiTietDonHang, KhachHang khachHang) {
		this.ngayTao = ngayTao;
		this.nguoiNhan = nguoiNhan;
		this.diaChiGiaoHang = diaChiGiaoHang;
		this.thoiGianGiaoHang = thoiGianGiaoHang;
		this.xoa = xoa;
		this.hinhThucThanhToan = hinhThucThanhToan;
		this.trangThai = trangThai;
		this.dsChiTietDonHang = dsChiTietDonHang;
		this.khachHang = khachHang;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getNgayTao() {
		return this.ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		this.ngayTao = ngayTao;
	}

	public NguoiNhan getNguoiNhan() {
		return this.nguoiNhan;
	}

	public void setNguoiNhan(NguoiNhan nguoiNhan) {
		this.nguoiNhan = nguoiNhan;
	}

	public String getDiaChiGiaoHang() {
		return this.diaChiGiaoHang;
	}

	public void setDiaChiGiaoHang(String diaChiGiaoHang) {
		this.diaChiGiaoHang = diaChiGiaoHang;
	}

	public Date getThoiGianGiaoHang() {
		return this.thoiGianGiaoHang;
	}

	public void setThoiGianGiaoHang(Date thoiGianGiaoHang) {
		this.thoiGianGiaoHang = thoiGianGiaoHang;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

	public HinhThucThanhToan getHinhThucThanhToan() {
		return this.hinhThucThanhToan;
	}

	public void setHinhThucThanhToan(HinhThucThanhToan hinhThucThanhToan) {
		this.hinhThucThanhToan = hinhThucThanhToan;
	}

	public TrangThaiDonHang getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(TrangThaiDonHang trangThai) {
		this.trangThai = trangThai;
	}

	public Set<ChiTietDonHang> getDsChiTietDonHang() {
		return this.dsChiTietDonHang;
	}

	public void setDsChiTietDonHang(Set<ChiTietDonHang> dsChiTietDonHang) {
		this.dsChiTietDonHang = dsChiTietDonHang;
	}

	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

}
