package qt.dto;

// Generated Jun 21, 2010 1:02:40 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GopY generated by hbm2java
 */
public class GopY implements java.io.Serializable {

	private Integer id;
	private String tieuDe;
	private String noiDung;
	private Date ngayTao;
	private boolean hienThi;
	private boolean xoa;
	private TrangThaiGopY trangThaiGopY;
	private KhachHang khachHang;

	public GopY() {
	}

	public GopY(String tieuDe, String noiDung, boolean hienThi, boolean xoa) {
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
		this.hienThi = hienThi;
		this.xoa = xoa;
	}

	public GopY(String tieuDe, String noiDung, Date ngayTao, boolean hienThi,
			boolean xoa, TrangThaiGopY trangThaiGopY, KhachHang khachHang) {
		this.tieuDe = tieuDe;
		this.noiDung = noiDung;
		this.ngayTao = ngayTao;
		this.hienThi = hienThi;
		this.xoa = xoa;
		this.trangThaiGopY = trangThaiGopY;
		this.khachHang = khachHang;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTieuDe() {
		return this.tieuDe;
	}

	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}

	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	public Date getNgayTao() {
		return this.ngayTao;
	}

	public void setNgayTao(Date ngayTao) {
		this.ngayTao = ngayTao;
	}

	public boolean isHienThi() {
		return this.hienThi;
	}

	public void setHienThi(boolean hienThi) {
		this.hienThi = hienThi;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

	public TrangThaiGopY getTrangThaiGopY() {
		return this.trangThaiGopY;
	}

	public void setTrangThaiGopY(TrangThaiGopY trangThaiGopY) {
		this.trangThaiGopY = trangThaiGopY;
	}

	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

}
