package qt.dto;

// Generated Jun 8, 2010 3:50:20 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * HeDieuHanh generated by hbm2java
 */
@SuppressWarnings("serial")
public class HeDieuHanh implements java.io.Serializable {

	private Integer id;
	private String ten;
	private String phienBan;
	private Set<DienThoai> dsDienThoai = new HashSet<DienThoai>(0);

	public HeDieuHanh() {
	}

	public HeDieuHanh(String ten) {
		this.ten = ten;
	}

	public HeDieuHanh(String ten, String phienBan, Set<DienThoai> dsDienThoai) {
		this.ten = ten;
		this.phienBan = phienBan;
		this.dsDienThoai = dsDienThoai;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public String getPhienBan() {
		return this.phienBan;
	}

	public void setPhienBan(String phienBan) {
		this.phienBan = phienBan;
	}

	public Set<DienThoai> getDsDienThoai() {
		return this.dsDienThoai;
	}

	public void setDsDienThoai(Set<DienThoai> dsDienThoai) {
		this.dsDienThoai = dsDienThoai;
	}

}
