package qt.dto;

// Generated Jun 12, 2010 11:48:25 PM by Hibernate Tools 3.3.0.GA

/**
 * KetNoi generated by hbm2java
 */
@SuppressWarnings("serial")
public class KetNoi implements java.io.Serializable {

	private boolean haiSim;
	private boolean GPRS;
	private boolean trinhDuyet;
	private boolean EDGE;
	private String hoTro3G;
	private boolean UMTS;
	private boolean WCDMA;
	private String wifi;
	private String GPS;
	private boolean hongNgoai;
	private boolean bluetooth;
	private boolean USB;

	public KetNoi() {
	}

	public KetNoi(boolean haiSim, boolean GPRS, boolean trinhDuyet,
			boolean EDGE, String hoTro3G, boolean UMTS, boolean WCDMA,
			String wifi, String GPS, boolean hongNgoai, boolean bluetooth,
			boolean USB) {
		this.haiSim = haiSim;
		this.GPRS = GPRS;
		this.trinhDuyet = trinhDuyet;
		this.EDGE = EDGE;
		this.hoTro3G = hoTro3G;
		this.UMTS = UMTS;
		this.WCDMA = WCDMA;
		this.wifi = wifi;
		this.GPS = GPS;
		this.hongNgoai = hongNgoai;
		this.bluetooth = bluetooth;
		this.USB = USB;
	}

	public boolean isHaiSim() {
		return this.haiSim;
	}

	public void setHaiSim(boolean haiSim) {
		this.haiSim = haiSim;
	}

	public boolean isGPRS() {
		return this.GPRS;
	}

	public void setGPRS(boolean GPRS) {
		this.GPRS = GPRS;
	}

	public boolean isTrinhDuyet() {
		return this.trinhDuyet;
	}

	public void setTrinhDuyet(boolean trinhDuyet) {
		this.trinhDuyet = trinhDuyet;
	}

	public boolean isEDGE() {
		return this.EDGE;
	}

	public void setEDGE(boolean EDGE) {
		this.EDGE = EDGE;
	}

	public String getHoTro3G() {
		return this.hoTro3G;
	}

	public void setHoTro3G(String hoTro3G) {
		this.hoTro3G = hoTro3G;
	}

	public boolean isUMTS() {
		return this.UMTS;
	}

	public void setUMTS(boolean UMTS) {
		this.UMTS = UMTS;
	}

	public boolean isWCDMA() {
		return this.WCDMA;
	}

	public void setWCDMA(boolean WCDMA) {
		this.WCDMA = WCDMA;
	}

	public String getWifi() {
		return this.wifi;
	}

	public void setWifi(String wifi) {
		this.wifi = wifi;
	}

	public String getGPS() {
		return this.GPS;
	}

	public void setGPS(String GPS) {
		this.GPS = GPS;
	}

	public boolean isHongNgoai() {
		return this.hongNgoai;
	}

	public void setHongNgoai(boolean hongNgoai) {
		this.hongNgoai = hongNgoai;
	}

	public boolean isBluetooth() {
		return this.bluetooth;
	}

	public void setBluetooth(boolean bluetooth) {
		this.bluetooth = bluetooth;
	}

	public boolean isUSB() {
		return this.USB;
	}

	public void setUSB(boolean USB) {
		this.USB = USB;
	}

}
