package qt.dto;

// Generated May 27, 2010 8:56:45 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * KhachHang generated by hbm2java
 */
@SuppressWarnings("serial")
public class KhachHang extends qt.dto.Account implements java.io.Serializable {

	private Set<GopY> dsGopY = new HashSet<GopY>(0);
	private Set<DonHang> dsDonHang = new HashSet<DonHang>(0);
	private Set<NhanXetDienThoai> dsNhanXetDienThoai = new HashSet<NhanXetDienThoai>(
			0);

	public KhachHang() {
	}

	public KhachHang(String username, String pass, Integer trangThai,
			String ho, String ten, String email, boolean xoa) {
		super(username, pass, trangThai, ho, ten, email, xoa);
	}

	public KhachHang(String username, String pass, Integer trangThai,
			String ho, String dem, String ten, String email, boolean xoa,
			Set<GopY> dsGopY, Set<DonHang> dsDonHang,
			Set<NhanXetDienThoai> dsNhanXetDienThoai) {
		super(username, pass, trangThai, ho, dem, ten, email, xoa);
		this.dsGopY = dsGopY;
		this.dsDonHang = dsDonHang;
		this.dsNhanXetDienThoai = dsNhanXetDienThoai;
	}

	public Set<GopY> getDsGopY() {
		return this.dsGopY;
	}

	public void setDsGopY(Set<GopY> dsGopY) {
		this.dsGopY = dsGopY;
	}

	public Set<DonHang> getDsDonHang() {
		return this.dsDonHang;
	}

	public void setDsDonHang(Set<DonHang> dsDonHang) {
		this.dsDonHang = dsDonHang;
	}

	public Set<NhanXetDienThoai> getDsNhanXetDienThoai() {
		return this.dsNhanXetDienThoai;
	}

	public void setDsNhanXetDienThoai(Set<NhanXetDienThoai> dsNhanXetDienThoai) {
		this.dsNhanXetDienThoai = dsNhanXetDienThoai;
	}

}
