package qt.dto;

// Generated Jun 20, 2010 4:44:09 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * LoaiPhuKien generated by hbm2java
 */
public class LoaiPhuKien implements java.io.Serializable {

	private Integer id;
	private String ten;
	private Set<PhuKien> dsPhuKien = new HashSet<PhuKien>(0);

	public LoaiPhuKien() {
	}

	public LoaiPhuKien(String ten) {
		this.ten = ten;
	}

	public LoaiPhuKien(String ten, Set<PhuKien> dsPhuKien) {
		this.ten = ten;
		this.dsPhuKien = dsPhuKien;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	public Set<PhuKien> getDsPhuKien() {
		return this.dsPhuKien;
	}

	public void setDsPhuKien(Set<PhuKien> dsPhuKien) {
		this.dsPhuKien = dsPhuKien;
	}

}
