package qt.dto;

// Generated Jun 17, 2010 10:03:17 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * LoaiTinTuc generated by hbm2java
 */
public class LoaiTinTuc implements java.io.Serializable {

	private Integer id;
	private String loaiTin;
	private Set<TinTuc> dsTinTuc = new HashSet<TinTuc>(0);

	public LoaiTinTuc() {
	}

	public LoaiTinTuc(String loaiTin) {
		this.loaiTin = loaiTin;
	}

	public LoaiTinTuc(String loaiTin, Set<TinTuc> dsTinTuc) {
		this.loaiTin = loaiTin;
		this.dsTinTuc = dsTinTuc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoaiTin() {
		return this.loaiTin;
	}

	public void setLoaiTin(String loaiTin) {
		this.loaiTin = loaiTin;
	}

	public Set<TinTuc> getDsTinTuc() {
		return this.dsTinTuc;
	}

	public void setDsTinTuc(Set<TinTuc> dsTinTuc) {
		this.dsTinTuc = dsTinTuc;
	}

}
