package qt.dto;

// Generated Jun 20, 2010 4:44:09 PM by Hibernate Tools 3.3.0.GA

/**
 * LuuTru generated by hbm2java
 */
public class LuuTru implements java.io.Serializable {

	private String danhBa;
	private String tinNhan;
	private String boNhoTrong;
	private String theNho;

	public LuuTru() {
	}

	public LuuTru(String danhBa, String tinNhan) {
		this.danhBa = danhBa;
		this.tinNhan = tinNhan;
	}

	public LuuTru(String danhBa, String tinNhan, String boNhoTrong,
			String theNho) {
		this.danhBa = danhBa;
		this.tinNhan = tinNhan;
		this.boNhoTrong = boNhoTrong;
		this.theNho = theNho;
	}

	public String getDanhBa() {
		return this.danhBa;
	}

	public void setDanhBa(String danhBa) {
		this.danhBa = danhBa;
	}

	public String getTinNhan() {
		return this.tinNhan;
	}

	public void setTinNhan(String tinNhan) {
		this.tinNhan = tinNhan;
	}

	public String getBoNhoTrong() {
		return this.boNhoTrong;
	}

	public void setBoNhoTrong(String boNhoTrong) {
		this.boNhoTrong = boNhoTrong;
	}

	public String getTheNho() {
		return this.theNho;
	}

	public void setTheNho(String theNho) {
		this.theNho = theNho;
	}

}
