package qt.dto;

// Generated May 27, 2010 8:56:45 PM by Hibernate Tools 3.3.0.GA

/**
 * NhanVienQuanLy generated by hbm2java
 */
@SuppressWarnings("serial")
public class NhanVienQuanLy extends qt.dto.Account implements
		java.io.Serializable {

	private String cmnd;
	private String diaChi;
	private String soDienThoai;

	public NhanVienQuanLy() {
	}

	public NhanVienQuanLy(String username, String pass, Integer trangThai,
			String ho, String ten, String email, boolean xoa, String cmnd,
			String diaChi, String soDienThoai) {
		super(username, pass, trangThai, ho, ten, email, xoa);
		this.cmnd = cmnd;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
	}

	public NhanVienQuanLy(String username, String pass, Integer trangThai,
			String ho, String dem, String ten, String email, boolean xoa,
			String cmnd, String diaChi, String soDienThoai) {
		super(username, pass, trangThai, ho, dem, ten, email, xoa);
		this.cmnd = cmnd;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
	}

	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

}
