package qt.dto;

// Generated Jun 21, 2010 1:02:40 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.Set;

/**
 * NhanVienQuanLy generated by hbm2java
 */
public class NhanVienQuanLy extends qt.dto.NhanVien implements
		java.io.Serializable {

	public NhanVienQuanLy() {
	}

	public NhanVienQuanLy(String username, String pass, Integer trangThai,
			String ho, String ten, String email, Integer gioiTinh, boolean xoa,
			String cmnd, Date ngaySinh, String diaChi, String dienThoai,
			Double luong) {
		super(username, pass, trangThai, ho, ten, email, gioiTinh, xoa, cmnd,
				ngaySinh, diaChi, dienThoai, luong);
	}

	public NhanVienQuanLy(String username, String pass, Integer trangThai,
			String ho, String dem, String ten, String email, Integer gioiTinh,
			boolean xoa, String cmnd, Date ngaySinh, String diaChi,
			String dienThoai, Double luong,
			Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai,
			Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien) {
		super(username, pass, trangThai, ho, dem, ten, email, gioiTinh, xoa,
				cmnd, ngaySinh, diaChi, dienThoai, luong, dsPhieuNhapDienThoai,
				dsPhieuNhapPhuKien);
	}

}
