package qt.dto;

// Generated Jun 20, 2010 4:44:09 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.Set;

/**
 * NhanVienBanHang generated by hbm2java
 */
public class NhanVienBanHang extends qt.dto.NhanVien implements
		java.io.Serializable {

	public NhanVienBanHang() {
	}

	public NhanVienBanHang(String username, String pass, Integer trangThai,
			String ho, String ten, String email, Integer gioiTinh, boolean xoa,
			String cmnd, Date ngaySinh, String diaChi, String dienThoai,
			double luong) {
		super(username, pass, trangThai, ho, ten, email, gioiTinh, xoa, cmnd,
				ngaySinh, diaChi, dienThoai, luong);
	}

	public NhanVienBanHang(String username, String pass, Integer trangThai,
			String ho, String dem, String ten, String email, Integer gioiTinh,
			boolean xoa, String cmnd, Date ngaySinh, String diaChi,
			String dienThoai, double luong,
			Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai,
			Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien) {
		super(username, pass, trangThai, ho, dem, ten, email, gioiTinh, xoa,
				cmnd, ngaySinh, diaChi, dienThoai, luong, dsPhieuNhapDienThoai,
				dsPhieuNhapPhuKien);
	}

}
