package qt.dto;

// Generated Jun 21, 2010 1:02:40 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhanVien generated by hbm2java
 */
public class NhanVien extends qt.dto.Account implements java.io.Serializable {

	private String cmnd;
	private Date ngaySinh;
	private String diaChi;
	private String dienThoai;
	private Double luong;
	private Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai = new HashSet<PhieuNhapDienThoai>(
			0);
	private Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien = new HashSet<PhieuNhapPhuKien>(
			0);

	public NhanVien() {
	}

	public NhanVien(String username, String pass, Integer trangThai, String ho,
			String ten, String email, Integer gioiTinh, boolean xoa,
			String cmnd, Date ngaySinh, String diaChi, String dienThoai,
			Double luong) {
		super(username, pass, trangThai, ho, ten, email, gioiTinh, xoa);
		this.cmnd = cmnd;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.luong = luong;
	}

	public NhanVien(String username, String pass, Integer trangThai, String ho,
			String dem, String ten, String email, Integer gioiTinh,
			boolean xoa, String cmnd, Date ngaySinh, String diaChi,
			String dienThoai, Double luong,
			Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai,
			Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien) {
		super(username, pass, trangThai, ho, dem, ten, email, gioiTinh, xoa);
		this.cmnd = cmnd;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.dienThoai = dienThoai;
		this.luong = luong;
		this.dsPhieuNhapDienThoai = dsPhieuNhapDienThoai;
		this.dsPhieuNhapPhuKien = dsPhieuNhapPhuKien;
	}

	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	public Double getLuong() {
		return this.luong;
	}

	public void setLuong(Double luong) {
		this.luong = luong;
	}

	public Set<PhieuNhapDienThoai> getDsPhieuNhapDienThoai() {
		return this.dsPhieuNhapDienThoai;
	}

	public void setDsPhieuNhapDienThoai(
			Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai) {
		this.dsPhieuNhapDienThoai = dsPhieuNhapDienThoai;
	}

	public Set<PhieuNhapPhuKien> getDsPhieuNhapPhuKien() {
		return this.dsPhieuNhapPhuKien;
	}

	public void setDsPhieuNhapPhuKien(Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien) {
		this.dsPhieuNhapPhuKien = dsPhieuNhapPhuKien;
	}

}
