package qt.dto;

// Generated Jun 12, 2010 11:48:25 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhanVien generated by hbm2java
 */
@SuppressWarnings("serial")
public class NhanVien extends qt.dto.Account implements java.io.Serializable {

	private String cmnd;
	private Date ngaySinh;
	private String diaChi;
	private String soDienThoai;
	private Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai = new HashSet<PhieuNhapDienThoai>(
			0);
	private Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien = new HashSet<PhieuNhapPhuKien>(
			0);

	public NhanVien() {
	}

	public NhanVien(String username, String pass, Integer trangThai, String ho,
			String ten, String email, Integer gioiTinh, boolean xoa,
			String cmnd, Date ngaySinh, String diaChi, String soDienThoai) {
		super(username, pass, trangThai, ho, ten, email, gioiTinh, xoa);
		this.cmnd = cmnd;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
	}

	public NhanVien(String username, String pass, Integer trangThai, String ho,
			String dem, String ten, String email, Integer gioiTinh,
			boolean xoa, String cmnd, Date ngaySinh, String diaChi,
			String soDienThoai, Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai,
			Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien) {
		super(username, pass, trangThai, ho, dem, ten, email, gioiTinh, xoa);
		this.cmnd = cmnd;
		this.ngaySinh = ngaySinh;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.dsPhieuNhapDienThoai = dsPhieuNhapDienThoai;
		this.dsPhieuNhapPhuKien = dsPhieuNhapPhuKien;
	}

	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public Set<PhieuNhapDienThoai> getDsPhieuNhapDienThoai() {
		return this.dsPhieuNhapDienThoai;
	}

	public void setDsPhieuNhapDienThoai(
			Set<PhieuNhapDienThoai> dsPhieuNhapDienThoai) {
		this.dsPhieuNhapDienThoai = dsPhieuNhapDienThoai;
	}

	public Set<PhieuNhapPhuKien> getDsPhieuNhapPhuKien() {
		return this.dsPhieuNhapPhuKien;
	}

	public void setDsPhieuNhapPhuKien(Set<PhieuNhapPhuKien> dsPhieuNhapPhuKien) {
		this.dsPhieuNhapPhuKien = dsPhieuNhapPhuKien;
	}

}
