package qt.dto;

// Generated Jun 18, 2010 3:27:17 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PhieuNhapDienThoai generated by hbm2java
 */
public class PhieuNhapDienThoai implements java.io.Serializable {

	private Integer id;
	private Date ngayNhap;
	private NhanVien nhanVien;
	private NhaCungCap nhaCungCap;
	private Set<ChiTietPhieuNhapDienThoai> dsChiTietPhieuNhapDienThoai = new HashSet<ChiTietPhieuNhapDienThoai>(
			0);
	private boolean xoa;

	public PhieuNhapDienThoai() {
	}

	public PhieuNhapDienThoai(Date ngayNhap, boolean xoa) {
		this.ngayNhap = ngayNhap;
		this.xoa = xoa;
	}

	public PhieuNhapDienThoai(Date ngayNhap, NhanVien nhanVien,
			NhaCungCap nhaCungCap,
			Set<ChiTietPhieuNhapDienThoai> dsChiTietPhieuNhapDienThoai,
			boolean xoa) {
		this.ngayNhap = ngayNhap;
		this.nhanVien = nhanVien;
		this.nhaCungCap = nhaCungCap;
		this.dsChiTietPhieuNhapDienThoai = dsChiTietPhieuNhapDienThoai;
		this.xoa = xoa;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	public NhanVien getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	public NhaCungCap getNhaCungCap() {
		return this.nhaCungCap;
	}

	public void setNhaCungCap(NhaCungCap nhaCungCap) {
		this.nhaCungCap = nhaCungCap;
	}

	public Set<ChiTietPhieuNhapDienThoai> getDsChiTietPhieuNhapDienThoai() {
		return this.dsChiTietPhieuNhapDienThoai;
	}

	public void setDsChiTietPhieuNhapDienThoai(
			Set<ChiTietPhieuNhapDienThoai> dsChiTietPhieuNhapDienThoai) {
		this.dsChiTietPhieuNhapDienThoai = dsChiTietPhieuNhapDienThoai;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

}
