package qt.dto;

// Generated Jun 12, 2010 11:48:25 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PhieuNhapPhuKien generated by hbm2java
 */
@SuppressWarnings("serial")
public class PhieuNhapPhuKien implements java.io.Serializable {

	private Integer id;
	private Date ngayNhap;
	private boolean xoa;
	private NhanVien nhanVien;
	private NhaCungCap nhaCungCap;
	private Set<ChiTietPhieuNhapPhuKien> dsChiTietPhieuNhapPhuKien = new HashSet<ChiTietPhieuNhapPhuKien>(
			0);

	public PhieuNhapPhuKien() {
	}

	public PhieuNhapPhuKien(Date ngayNhap, boolean xoa) {
		this.ngayNhap = ngayNhap;
		this.xoa = xoa;
	}

	public PhieuNhapPhuKien(Date ngayNhap, boolean xoa, NhanVien nhanVien,
			NhaCungCap nhaCungCap,
			Set<ChiTietPhieuNhapPhuKien> dsChiTietPhieuNhapPhuKien) {
		this.ngayNhap = ngayNhap;
		this.xoa = xoa;
		this.nhanVien = nhanVien;
		this.nhaCungCap = nhaCungCap;
		this.dsChiTietPhieuNhapPhuKien = dsChiTietPhieuNhapPhuKien;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

	public NhanVien getNhanVien() {
		return this.nhanVien;
	}

	public void setNhanVien(NhanVien nhanVien) {
		this.nhanVien = nhanVien;
	}

	public NhaCungCap getNhaCungCap() {
		return this.nhaCungCap;
	}

	public void setNhaCungCap(NhaCungCap nhaCungCap) {
		this.nhaCungCap = nhaCungCap;
	}

	public Set<ChiTietPhieuNhapPhuKien> getDsChiTietPhieuNhapPhuKien() {
		return this.dsChiTietPhieuNhapPhuKien;
	}

	public void setDsChiTietPhieuNhapPhuKien(
			Set<ChiTietPhieuNhapPhuKien> dsChiTietPhieuNhapPhuKien) {
		this.dsChiTietPhieuNhapPhuKien = dsChiTietPhieuNhapPhuKien;
	}

}
