package qt.dto;

// Generated Jun 12, 2010 11:48:25 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * PhuKien generated by hbm2java
 */
@SuppressWarnings("serial")
public class PhuKien extends qt.dto.SanPham implements java.io.Serializable {

	private LoaiPhuKien loaiPhuKien;
	private String mauSac;
	private String tinhNang;
	private String huongDanSuDung;
	private Set<DienThoai> dsDienThoaiTuongThich = new HashSet<DienThoai>(0);
	private Set<ChiTietPhieuNhapPhuKien> dsChiTietNhapPhuKien = new HashSet<ChiTietPhieuNhapPhuKien>(
			0);
	private Set<TinGiamGiaPhuKien> dsTinGiamGiaPhuKien = new HashSet<TinGiamGiaPhuKien>(
			0);

	public PhuKien() {
	}

	public PhuKien(String ten, double giaNhap, double giaHienHanh,
			String tinhNang) {
		super(ten, giaNhap, giaHienHanh);
		this.tinhNang = tinhNang;
	}

	public PhuKien(String ten, double giaNhap, double giaHienHanh, int baoHanh,
			boolean xoa, String hinhAnh, Set<NhaCungCap> dsNhaCungCap,
			Set<ChiTietDonHang> dsChiTietDonHang,
			TinhTrangSanPham tinhTrangSanPham, Set<ChiTietHinhAnh> dsHinhAnh,
			LoaiPhuKien loaiPhuKien, String mauSac, String tinhNang,
			String huongDanSuDung, Set<DienThoai> dsDienThoaiTuongThich,
			Set<ChiTietPhieuNhapPhuKien> dsChiTietNhapPhuKien,
			Set<TinGiamGiaPhuKien> dsTinGiamGiaPhuKien) {
		super(ten, giaNhap, giaHienHanh, baoHanh, xoa, hinhAnh, dsNhaCungCap,
				dsChiTietDonHang, tinhTrangSanPham, dsHinhAnh);
		this.loaiPhuKien = loaiPhuKien;
		this.mauSac = mauSac;
		this.tinhNang = tinhNang;
		this.huongDanSuDung = huongDanSuDung;
		this.dsDienThoaiTuongThich = dsDienThoaiTuongThich;
		this.dsChiTietNhapPhuKien = dsChiTietNhapPhuKien;
		this.dsTinGiamGiaPhuKien = dsTinGiamGiaPhuKien;
	}

	public LoaiPhuKien getLoaiPhuKien() {
		return this.loaiPhuKien;
	}

	public void setLoaiPhuKien(LoaiPhuKien loaiPhuKien) {
		this.loaiPhuKien = loaiPhuKien;
	}

	public String getMauSac() {
		return this.mauSac;
	}

	public void setMauSac(String mauSac) {
		this.mauSac = mauSac;
	}

	public String getTinhNang() {
		return this.tinhNang;
	}

	public void setTinhNang(String tinhNang) {
		this.tinhNang = tinhNang;
	}

	public String getHuongDanSuDung() {
		return this.huongDanSuDung;
	}

	public void setHuongDanSuDung(String huongDanSuDung) {
		this.huongDanSuDung = huongDanSuDung;
	}

	public Set<DienThoai> getDsDienThoaiTuongThich() {
		return this.dsDienThoaiTuongThich;
	}

	public void setDsDienThoaiTuongThich(Set<DienThoai> dsDienThoaiTuongThich) {
		this.dsDienThoaiTuongThich = dsDienThoaiTuongThich;
	}

	public Set<ChiTietPhieuNhapPhuKien> getDsChiTietNhapPhuKien() {
		return this.dsChiTietNhapPhuKien;
	}

	public void setDsChiTietNhapPhuKien(
			Set<ChiTietPhieuNhapPhuKien> dsChiTietNhapPhuKien) {
		this.dsChiTietNhapPhuKien = dsChiTietNhapPhuKien;
	}

	public Set<TinGiamGiaPhuKien> getDsTinGiamGiaPhuKien() {
		return this.dsTinGiamGiaPhuKien;
	}

	public void setDsTinGiamGiaPhuKien(
			Set<TinGiamGiaPhuKien> dsTinGiamGiaPhuKien) {
		this.dsTinGiamGiaPhuKien = dsTinGiamGiaPhuKien;
	}

}
