package qt.dto;

// Generated Jun 11, 2010 1:35:04 AM by Hibernate Tools 3.3.0.GA

/**
 * Pin generated by hbm2java
 */
public class Pin implements java.io.Serializable {

	private String loaiPin;
	private Integer dungLuong;
	private Integer thoiGianDamThoai;
	private Integer thoiGianCho;

	public Pin() {
	}

	public Pin(String loaiPin, Integer dungLuong, Integer thoiGianDamThoai,
			Integer thoiGianCho) {
		this.loaiPin = loaiPin;
		this.dungLuong = dungLuong;
		this.thoiGianDamThoai = thoiGianDamThoai;
		this.thoiGianCho = thoiGianCho;
	}

	public String getLoaiPin() {
		return this.loaiPin;
	}

	public void setLoaiPin(String loaiPin) {
		this.loaiPin = loaiPin;
	}

	public Integer getDungLuong() {
		return this.dungLuong;
	}

	public void setDungLuong(Integer dungLuong) {
		this.dungLuong = dungLuong;
	}

	public Integer getThoiGianDamThoai() {
		return this.thoiGianDamThoai;
	}

	public void setThoiGianDamThoai(Integer thoiGianDamThoai) {
		this.thoiGianDamThoai = thoiGianDamThoai;
	}

	public Integer getThoiGianCho() {
		return this.thoiGianCho;
	}

	public void setThoiGianCho(Integer thoiGianCho) {
		this.thoiGianCho = thoiGianCho;
	}

}
