package qt.dto;

// Generated Jun 17, 2010 12:35:19 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * TinGiamGiaPhuKien generated by hbm2java
 */
public class TinGiamGiaPhuKien implements java.io.Serializable {

	private Integer id;
	private PhuKien phuKien;
	private double mucGiam;
	private String chiTiet;
	private Date ngayBatDau;
	private Date ngayKetThuc;
	private boolean hienThi;
	private boolean xoa;

	public TinGiamGiaPhuKien() {
	}

	public TinGiamGiaPhuKien(double mucGiam, Date ngayBatDau, Date ngayKetThuc,
			boolean hienThi, boolean xoa) {
		this.mucGiam = mucGiam;
		this.ngayBatDau = ngayBatDau;
		this.ngayKetThuc = ngayKetThuc;
		this.hienThi = hienThi;
		this.xoa = xoa;
	}

	public TinGiamGiaPhuKien(PhuKien phuKien, double mucGiam, String chiTiet,
			Date ngayBatDau, Date ngayKetThuc, boolean hienThi, boolean xoa) {
		this.phuKien = phuKien;
		this.mucGiam = mucGiam;
		this.chiTiet = chiTiet;
		this.ngayBatDau = ngayBatDau;
		this.ngayKetThuc = ngayKetThuc;
		this.hienThi = hienThi;
		this.xoa = xoa;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PhuKien getPhuKien() {
		return this.phuKien;
	}

	public void setPhuKien(PhuKien phuKien) {
		this.phuKien = phuKien;
	}

	public double getMucGiam() {
		return this.mucGiam;
	}

	public void setMucGiam(double mucGiam) {
		this.mucGiam = mucGiam;
	}

	public String getChiTiet() {
		return this.chiTiet;
	}

	public void setChiTiet(String chiTiet) {
		this.chiTiet = chiTiet;
	}

	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	public Date getNgayKetThuc() {
		return this.ngayKetThuc;
	}

	public void setNgayKetThuc(Date ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}

	public boolean isHienThi() {
		return this.hienThi;
	}

	public void setHienThi(boolean hienThi) {
		this.hienThi = hienThi;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

}
