package qt.dto;

// Generated Jun 8, 2010 3:50:20 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TinhTrangSanPham generated by hbm2java
 */
@SuppressWarnings("serial")
public class TinhTrangSanPham implements java.io.Serializable {

	private Integer id;
	private String tinhTrang;
	private Set<SanPham> dsSanPham = new HashSet<SanPham>(0);

	public TinhTrangSanPham() {
	}

	public TinhTrangSanPham(String tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	public TinhTrangSanPham(String tinhTrang, Set<SanPham> dsSanPham) {
		this.tinhTrang = tinhTrang;
		this.dsSanPham = dsSanPham;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(String tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	public Set<SanPham> getDsSanPham() {
		return this.dsSanPham;
	}

	public void setDsSanPham(Set<SanPham> dsSanPham) {
		this.dsSanPham = dsSanPham;
	}

}
