package qt.dto;

// Generated May 27, 2010 8:56:45 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * TinTuc generated by hbm2java
 */
@SuppressWarnings("serial")
public class TinTuc implements java.io.Serializable {

	private Integer id;
	private Date ngayDang;
	private String noiDung;
	private boolean hienThi;
	private boolean xoa;
	private LoaiTinTuc loaiTinTuc;

	public TinTuc() {
	}

	public TinTuc(Date ngayDang, String noiDung, boolean hienThi, boolean xoa) {
		this.ngayDang = ngayDang;
		this.noiDung = noiDung;
		this.hienThi = hienThi;
		this.xoa = xoa;
	}

	public TinTuc(Date ngayDang, String noiDung, boolean hienThi, boolean xoa,
			LoaiTinTuc loaiTinTuc) {
		this.ngayDang = ngayDang;
		this.noiDung = noiDung;
		this.hienThi = hienThi;
		this.xoa = xoa;
		this.loaiTinTuc = loaiTinTuc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getNgayDang() {
		return this.ngayDang;
	}

	public void setNgayDang(Date ngayDang) {
		this.ngayDang = ngayDang;
	}

	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	public boolean isHienThi() {
		return this.hienThi;
	}

	public void setHienThi(boolean hienThi) {
		this.hienThi = hienThi;
	}

	public boolean isXoa() {
		return this.xoa;
	}

	public void setXoa(boolean xoa) {
		this.xoa = xoa;
	}

	public LoaiTinTuc getLoaiTinTuc() {
		return this.loaiTinTuc;
	}

	public void setLoaiTinTuc(LoaiTinTuc loaiTinTuc) {
		this.loaiTinTuc = loaiTinTuc;
	}

}
