package qt.dto;

// Generated Jun 11, 2010 1:35:04 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TrangThaiGopY generated by hbm2java
 */
public class TrangThaiGopY implements java.io.Serializable {

	private Integer id;
	private String trangThai;
	private Set<GopY> dsGopY = new HashSet<GopY>(0);

	public TrangThaiGopY() {
	}

	public TrangThaiGopY(String trangThai) {
		this.trangThai = trangThai;
	}

	public TrangThaiGopY(String trangThai, Set<GopY> dsGopY) {
		this.trangThai = trangThai;
		this.dsGopY = dsGopY;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(String trangThai) {
		this.trangThai = trangThai;
	}

	public Set<GopY> getDsGopY() {
		return this.dsGopY;
	}

	public void setDsGopY(Set<GopY> dsGopY) {
		this.dsGopY = dsGopY;
	}

}
