package qt.dto;

// Generated Jun 17, 2010 12:35:19 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TrangThaiDonHang generated by hbm2java
 */
public class TrangThaiDonHang implements java.io.Serializable {

	private Integer id;
	private String trangThai;
	private Set<DonHang> dsDonHang = new HashSet<DonHang>(0);

	public TrangThaiDonHang() {
	}

	public TrangThaiDonHang(String trangThai) {
		this.trangThai = trangThai;
	}

	public TrangThaiDonHang(String trangThai, Set<DonHang> dsDonHang) {
		this.trangThai = trangThai;
		this.dsDonHang = dsDonHang;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(String trangThai) {
		this.trangThai = trangThai;
	}

	public Set<DonHang> getDsDonHang() {
		return this.dsDonHang;
	}

	public void setDsDonHang(Set<DonHang> dsDonHang) {
		this.dsDonHang = dsDonHang;
	}

}
